
#      __ _        _                             ___
#   /\ \ (_)_ __  (_) __ _  __ _  ___   /\/\    / __\
#  /  \/ / | '_ \ | |/ _` |/ _` |/ _ \ /    \  / /
# / /\  /| | | | || | (_| | (_| | (_) / /\/\ \/ /___
# \_\ \/ |_|_| |_|/ |\__,_|\__, |\___/\/    \/\____/
#               |__/       |___/

# NinjagoMC Config


# PREFIXES ----------------------------------------------------------------------------------------------
# The main prefix for plugin messages
prefix: "§8[§aNinjago§2MC§8]"
# -------------------------------------------------------------------------------------------------------


# OPTIONS -----------------------------------------------------------------------------------------------
# Defines if a player with no element gets a random element when joining
random-element: true
# Defines after how many seconds the player is given the random element after joining
random-element-delay: 600
# -------------------------------------------------------------------------------------------------------