
#      __ _        _                             ___
#   /\ \ (_)_ __  (_) __ _  __ _  ___   /\/\    / __\
#  /  \/ / | '_ \ | |/ _` |/ _` |/ _ \ /    \  / /
# / /\  /| | | | || | (_| | (_| | (_) / /\/\ \/ /___
# \_\ \/ |_|_| |_|/ |\__,_|\__, |\___/\/    \/\____/
#               |__/       |___/

# NinjagoMC Config


# PREFIXES ----------------------------------------------------------------------------------------------
# The main prefix for plugin messages
prefix: "§8[&aNinjagoMC§8]"
# -------------------------------------------------------------------------------------------------------
